### ISSUE TITLE
error: unrecognized command line option ‘-rdynamic’

### ISSUE THREAD

**Issue by lsy563193** [chintal/toolchains#1]
hello! I meet some troubel like this when I built: 
Linking C executable firmware-msp430f5529.elf
msp430-elf-gcc: error: unrecognized command line option ‘-rdynamic’

It seem doesn't support "-rdynamic".
how can i emove "-rdynamic" from link options

**Comment by chintal** [comment]
The cmake toolchain files here don't add -rdynamic to the link flags. Can you post more information about what exactly is the configuration you're using? Your CMakeLists.txt file would probably be a good start.

**Comment by chintal** [comment]
OP seem to have worked out the issue on his own. 

Closing.
